health:
  check:
    message: book service is up now from git hub book service updated3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
